<?php

return array (
  'type' => 'extension',
  'name' => 'mongodb',
  'meta' => 
  array (
    'type' => 'extension',
    'name' => 'mongodb',
    'description' => '',
    'keywords' => 
    array (
    ),
    'added' => '0.0',
    'deprecated' => 
    \ReflectionExtension::__set_state(array(
       'name' => 'mongodb',
    )),
    'removed' => NULL,
    'version' => '1.19.3',
    'resources' => 
    array (
      0 => 
      array (
        'name' => 'mongodb extension (php.net)',
        'url' => 'https://www.php.net/manual/book.mongodb.php',
      ),
    ),
  ),
  'classes' => 
  array (
    0 => 'MongoDB\\BSON\\Type',
    1 => 'MongoDB\\BSON\\Serializable',
    2 => 'MongoDB\\BSON\\Unserializable',
    3 => 'MongoDB\\BSON\\BinaryInterface',
    4 => 'MongoDB\\BSON\\Decimal128Interface',
    5 => 'MongoDB\\BSON\\JavascriptInterface',
    6 => 'MongoDB\\BSON\\MaxKeyInterface',
    7 => 'MongoDB\\BSON\\MinKeyInterface',
    8 => 'MongoDB\\BSON\\ObjectIdInterface',
    9 => 'MongoDB\\BSON\\RegexInterface',
    10 => 'MongoDB\\BSON\\TimestampInterface',
    11 => 'MongoDB\\BSON\\UTCDateTimeInterface',
    12 => 'MongoDB\\BSON\\Iterator',
    13 => 'MongoDB\\BSON\\PackedArray',
    14 => 'MongoDB\\BSON\\Document',
    15 => 'MongoDB\\BSON\\Binary',
    16 => 'MongoDB\\BSON\\DBPointer',
    17 => 'MongoDB\\BSON\\Decimal128',
    18 => 'MongoDB\\BSON\\Int64',
    19 => 'MongoDB\\BSON\\Javascript',
    20 => 'MongoDB\\BSON\\MaxKey',
    21 => 'MongoDB\\BSON\\MinKey',
    22 => 'MongoDB\\BSON\\ObjectId',
    23 => 'MongoDB\\BSON\\Persistable',
    24 => 'MongoDB\\BSON\\Regex',
    25 => 'MongoDB\\BSON\\Symbol',
    26 => 'MongoDB\\BSON\\Timestamp',
    27 => 'MongoDB\\BSON\\Undefined',
    28 => 'MongoDB\\BSON\\UTCDateTime',
    29 => 'MongoDB\\Driver\\CursorInterface',
    30 => 'MongoDB\\Driver\\BulkWrite',
    31 => 'MongoDB\\Driver\\ClientEncryption',
    32 => 'MongoDB\\Driver\\Command',
    33 => 'MongoDB\\Driver\\Cursor',
    34 => 'MongoDB\\Driver\\CursorId',
    35 => 'MongoDB\\Driver\\Manager',
    36 => 'MongoDB\\Driver\\Query',
    37 => 'MongoDB\\Driver\\ReadConcern',
    38 => 'MongoDB\\Driver\\ReadPreference',
    39 => 'MongoDB\\Driver\\Server',
    40 => 'MongoDB\\Driver\\ServerApi',
    41 => 'MongoDB\\Driver\\ServerDescription',
    42 => 'MongoDB\\Driver\\TopologyDescription',
    43 => 'MongoDB\\Driver\\Session',
    44 => 'MongoDB\\Driver\\WriteConcern',
    45 => 'MongoDB\\Driver\\WriteConcernError',
    46 => 'MongoDB\\Driver\\WriteError',
    47 => 'MongoDB\\Driver\\WriteResult',
    48 => 'MongoDB\\Driver\\Exception\\Exception',
    49 => 'MongoDB\\Driver\\Exception\\RuntimeException',
    50 => 'MongoDB\\Driver\\Exception\\ServerException',
    51 => 'MongoDB\\Driver\\Exception\\ConnectionException',
    52 => 'MongoDB\\Driver\\Exception\\WriteException',
    53 => 'MongoDB\\Driver\\Exception\\AuthenticationException',
    54 => 'MongoDB\\Driver\\Exception\\BulkWriteException',
    55 => 'MongoDB\\Driver\\Exception\\CommandException',
    56 => 'MongoDB\\Driver\\Exception\\ConnectionTimeoutException',
    57 => 'MongoDB\\Driver\\Exception\\EncryptionException',
    58 => 'MongoDB\\Driver\\Exception\\ExecutionTimeoutException',
    59 => 'MongoDB\\Driver\\Exception\\InvalidArgumentException',
    60 => 'MongoDB\\Driver\\Exception\\LogicException',
    61 => 'MongoDB\\Driver\\Exception\\SSLConnectionException',
    62 => 'MongoDB\\Driver\\Exception\\UnexpectedValueException',
    63 => 'MongoDB\\Driver\\Monitoring\\Subscriber',
    64 => 'MongoDB\\Driver\\Monitoring\\CommandSubscriber',
    65 => 'MongoDB\\Driver\\Monitoring\\CommandFailedEvent',
    66 => 'MongoDB\\Driver\\Monitoring\\CommandStartedEvent',
    67 => 'MongoDB\\Driver\\Monitoring\\CommandSucceededEvent',
    68 => 'MongoDB\\Driver\\Monitoring\\LogSubscriber',
    69 => 'MongoDB\\Driver\\Monitoring\\SDAMSubscriber',
    70 => 'MongoDB\\Driver\\Monitoring\\ServerChangedEvent',
    71 => 'MongoDB\\Driver\\Monitoring\\ServerClosedEvent',
    72 => 'MongoDB\\Driver\\Monitoring\\ServerHeartbeatFailedEvent',
    73 => 'MongoDB\\Driver\\Monitoring\\ServerHeartbeatStartedEvent',
    74 => 'MongoDB\\Driver\\Monitoring\\ServerHeartbeatSucceededEvent',
    75 => 'MongoDB\\Driver\\Monitoring\\ServerOpeningEvent',
    76 => 'MongoDB\\Driver\\Monitoring\\TopologyChangedEvent',
    77 => 'MongoDB\\Driver\\Monitoring\\TopologyClosedEvent',
    78 => 'MongoDB\\Driver\\Monitoring\\TopologyOpeningEvent',
  ),
  'functions' => 
  array (
    'MongoDB\\BSON\\fromJSON' => 'MongoDB\\BSON\\fromJSON',
    'MongoDB\\BSON\\fromPHP' => 'MongoDB\\BSON\\fromPHP',
    'MongoDB\\BSON\\toCanonicalExtendedJSON' => 'MongoDB\\BSON\\toCanonicalExtendedJSON',
    'MongoDB\\BSON\\toJSON' => 'MongoDB\\BSON\\toJSON',
    'MongoDB\\BSON\\toPHP' => 'MongoDB\\BSON\\toPHP',
    'MongoDB\\BSON\\toRelaxedExtendedJSON' => 'MongoDB\\BSON\\toRelaxedExtendedJSON',
    'MongoDB\\Driver\\Monitoring\\addSubscriber' => 'MongoDB\\Driver\\Monitoring\\addSubscriber',
    'MongoDB\\Driver\\Monitoring\\mongoc_log' => 'MongoDB\\Driver\\Monitoring\\mongoc_log',
    'MongoDB\\Driver\\Monitoring\\removeSubscriber' => 'MongoDB\\Driver\\Monitoring\\removeSubscriber',
  ),
  'constants' => 
  array (
    'MONGODB_VERSION' => '1.19.3',
    'MONGODB_STABILITY' => 'stable',
  ),
  'dependencies' => 
  array (
  ),
  'ini' => 
  array (
    'mongodb.debug' => '',
  ),
);
