<?php

return array (
  'Traversable',
  'IteratorAggregate',
  'Iterator',
  'Serializable',
  'ArrayAccess',
  'Countable',
  'Stringable',
  'Throwable',
  'UnitEnum',
  'BackedEnum',
  'DateTimeInterface',
  'JsonSerializable',
  'Reflector',
  'RecursiveIterator',
  'OuterIterator',
  'SeekableIterator',
  'SplObserver',
  'SplSubject',
  'SessionHandlerInterface',
  'SessionIdInterface',
  'SessionUpdateTimestampHandlerInterface',
  'DOMParentNode',
  'DOMChildNode',
);
