<?php

return array (
  'type' => 'extension',
  'name' => 'dom',
  'meta' => 
  array (
    'type' => 'extension',
    'name' => 'dom',
    'description' => '',
    'keywords' => 
    array (
    ),
    'added' => '0.0',
    'deprecated' => 
    \ReflectionExtension::__set_state(array(
       'name' => 'dom',
    )),
    'removed' => NULL,
    'version' => '20031129',
    'resources' => 
    array (
      0 => 
      array (
        'name' => 'dom extension (php.net)',
        'url' => 'https://www.php.net/manual/book.dom.php',
      ),
    ),
  ),
  'classes' => 
  array (
    0 => 'Dom\\AdjacentPosition',
    1 => 'DOMException',
    2 => 'dom\\domexception',
    3 => 'DOMParentNode',
    4 => 'Dom\\ParentNode',
    5 => 'DOMChildNode',
    6 => 'Dom\\ChildNode',
    7 => 'DOMImplementation',
    8 => 'Dom\\Implementation',
    9 => 'DOMNode',
    10 => 'Dom\\Node',
    11 => 'DOMNameSpaceNode',
    12 => 'DOMDocumentFragment',
    13 => 'Dom\\DocumentFragment',
    14 => 'Dom\\Document',
    15 => 'DOMDocument',
    16 => 'Dom\\HTMLDocument',
    17 => 'Dom\\XMLDocument',
    18 => 'DOMNodeList',
    19 => 'Dom\\NodeList',
    20 => 'DOMNamedNodeMap',
    21 => 'Dom\\NamedNodeMap',
    22 => 'Dom\\DtdNamedNodeMap',
    23 => 'Dom\\HTMLCollection',
    24 => 'DOMCharacterData',
    25 => 'Dom\\CharacterData',
    26 => 'DOMAttr',
    27 => 'Dom\\Attr',
    28 => 'DOMElement',
    29 => 'Dom\\Element',
    30 => 'Dom\\HTMLElement',
    31 => 'DOMText',
    32 => 'Dom\\Text',
    33 => 'DOMComment',
    34 => 'Dom\\Comment',
    35 => 'DOMCdataSection',
    36 => 'Dom\\CDATASection',
    37 => 'DOMDocumentType',
    38 => 'Dom\\DocumentType',
    39 => 'DOMNotation',
    40 => 'Dom\\Notation',
    41 => 'DOMEntity',
    42 => 'Dom\\Entity',
    43 => 'DOMEntityReference',
    44 => 'Dom\\EntityReference',
    45 => 'DOMProcessingInstruction',
    46 => 'Dom\\ProcessingInstruction',
    47 => 'DOMXPath',
    48 => 'Dom\\XPath',
  ),
  'functions' => 
  array (
    'dom_import_simplexml' => 'dom_import_simplexml',
    'Dom\\import_simplexml' => 'Dom\\import_simplexml',
  ),
  'constants' => 
  array (
    'XML_ELEMENT_NODE' => 1,
    'XML_ATTRIBUTE_NODE' => 2,
    'XML_TEXT_NODE' => 3,
    'XML_CDATA_SECTION_NODE' => 4,
    'XML_ENTITY_REF_NODE' => 5,
    'XML_ENTITY_NODE' => 6,
    'XML_PI_NODE' => 7,
    'XML_COMMENT_NODE' => 8,
    'XML_DOCUMENT_NODE' => 9,
    'XML_DOCUMENT_TYPE_NODE' => 10,
    'XML_DOCUMENT_FRAG_NODE' => 11,
    'XML_NOTATION_NODE' => 12,
    'XML_HTML_DOCUMENT_NODE' => 13,
    'XML_DTD_NODE' => 14,
    'XML_ELEMENT_DECL_NODE' => 15,
    'XML_ATTRIBUTE_DECL_NODE' => 16,
    'XML_ENTITY_DECL_NODE' => 17,
    'XML_NAMESPACE_DECL_NODE' => 18,
    'XML_LOCAL_NAMESPACE' => 18,
    'XML_ATTRIBUTE_CDATA' => 1,
    'XML_ATTRIBUTE_ID' => 2,
    'XML_ATTRIBUTE_IDREF' => 3,
    'XML_ATTRIBUTE_IDREFS' => 4,
    'XML_ATTRIBUTE_ENTITY' => 6,
    'XML_ATTRIBUTE_NMTOKEN' => 7,
    'XML_ATTRIBUTE_NMTOKENS' => 8,
    'XML_ATTRIBUTE_ENUMERATION' => 9,
    'XML_ATTRIBUTE_NOTATION' => 10,
    'DOM_PHP_ERR' => 0,
    'DOM_INDEX_SIZE_ERR' => 1,
    'DOMSTRING_SIZE_ERR' => 2,
    'DOM_HIERARCHY_REQUEST_ERR' => 3,
    'DOM_WRONG_DOCUMENT_ERR' => 4,
    'DOM_INVALID_CHARACTER_ERR' => 5,
    'DOM_NO_DATA_ALLOWED_ERR' => 6,
    'DOM_NO_MODIFICATION_ALLOWED_ERR' => 7,
    'DOM_NOT_FOUND_ERR' => 8,
    'DOM_NOT_SUPPORTED_ERR' => 9,
    'DOM_INUSE_ATTRIBUTE_ERR' => 10,
    'DOM_INVALID_STATE_ERR' => 11,
    'DOM_SYNTAX_ERR' => 12,
    'DOM_INVALID_MODIFICATION_ERR' => 13,
    'DOM_NAMESPACE_ERR' => 14,
    'DOM_INVALID_ACCESS_ERR' => 15,
    'DOM_VALIDATION_ERR' => 16,
    'Dom\\INDEX_SIZE_ERR' => 1,
    'Dom\\STRING_SIZE_ERR' => 2,
    'Dom\\HIERARCHY_REQUEST_ERR' => 3,
    'Dom\\WRONG_DOCUMENT_ERR' => 4,
    'Dom\\INVALID_CHARACTER_ERR' => 5,
    'Dom\\NO_DATA_ALLOWED_ERR' => 6,
    'Dom\\NO_MODIFICATION_ALLOWED_ERR' => 7,
    'Dom\\NOT_FOUND_ERR' => 8,
    'Dom\\NOT_SUPPORTED_ERR' => 9,
    'Dom\\INUSE_ATTRIBUTE_ERR' => 10,
    'Dom\\INVALID_STATE_ERR' => 11,
    'Dom\\SYNTAX_ERR' => 12,
    'Dom\\INVALID_MODIFICATION_ERR' => 13,
    'Dom\\NAMESPACE_ERR' => 14,
    'Dom\\VALIDATION_ERR' => 16,
    'Dom\\HTML_NO_DEFAULT_NS' => 2147483648,
  ),
  'dependencies' => 
  array (
  ),
  'ini' => 
  array (
  ),
);
