<?php

return array (
  'type' => 'extension',
  'name' => 'zend_test',
  'meta' => 
  array (
    'type' => 'extension',
    'name' => 'zend_test',
    'description' => '',
    'keywords' => 
    array (
    ),
    'added' => '0.0',
    'deprecated' => 
    \ReflectionExtension::__set_state(array(
       'name' => 'zend_test',
    )),
    'removed' => NULL,
    'version' => '0.1.0',
    'resources' => 
    array (
      0 => 
      array (
        'name' => 'zend_test extension (php.net)',
        'url' => 'https://www.php.net/manual/book.zend_test.php',
      ),
    ),
  ),
  'classes' => 
  array (
    0 => '_ZendTestInterface',
    1 => '_ZendTestClass',
    2 => '_zendtestclassalias',
    3 => '_ZendTestChildClass',
    4 => 'ZendAttributeTest',
    5 => '_ZendTestTrait',
    6 => 'ZendTestAttribute',
    7 => 'ZendTestRepeatableAttribute',
    8 => 'ZendTestParameterAttribute',
    9 => 'ZendTestPropertyAttribute',
    10 => 'ZendTestAttributeWithArguments',
    11 => 'ZendTestClassWithMethodWithParameterAttribute',
    12 => 'ZendTestChildClassWithMethodWithParameterAttribute',
    13 => 'ZendTestClassWithPropertyAttribute',
    14 => 'ZendTestForbidDynamicCall',
    15 => 'ZendTestNS\\Foo',
    16 => 'ZendTestNS\\UnlikelyCompileError',
    17 => 'ZendTestNS\\NotUnlikelyCompileError',
    18 => 'ZendTestNS2\\Foo',
    19 => 'ZendTestNS2\\ZendSubNS\\Foo',
    20 => 'ZendTestUnitEnum',
    21 => 'ZendTestStringEnum',
    22 => 'ZendTestIntEnum',
    23 => '_ZendTestMagicCall',
    24 => '_ZendTestFiber',
    25 => 'ZendTest\\Iterators\\TraversableTest',
    26 => 'DoOperationNoCast',
    27 => 'LongCastableNoOperations',
    28 => 'FloatCastableNoOperations',
    29 => 'NumericCastableNoOperations',
    30 => 'DimensionHandlersNoArrayAccess',
  ),
  'functions' => 
  array (
    'zend_test_array_return' => 'zend_test_array_return',
    'zend_test_nullable_array_return' => 'zend_test_nullable_array_return',
    'zend_test_void_return' => 'zend_test_void_return',
    'zend_test_compile_string' => 'zend_test_compile_string',
    'zend_test_deprecated' => 'zend_test_deprecated',
    'zend_test_deprecated_attr' => 'zend_test_deprecated_attr',
    'zend_test_aliased' => 'zend_test_aliased',
    'zend_test_deprecated_aliased' => 'zend_test_deprecated_aliased',
    'zend_create_unterminated_string' => 'zend_create_unterminated_string',
    'zend_terminate_string' => 'zend_terminate_string',
    'zend_leak_variable' => 'zend_leak_variable',
    'zend_leak_bytes' => 'zend_leak_bytes',
    'zend_string_or_object' => 'zend_string_or_object',
    'zend_string_or_object_or_null' => 'zend_string_or_object_or_null',
    'zend_string_or_stdclass' => 'zend_string_or_stdclass',
    'zend_string_or_stdclass_or_null' => 'zend_string_or_stdclass_or_null',
    'zend_number_or_string' => 'zend_number_or_string',
    'zend_number_or_string_or_null' => 'zend_number_or_string_or_null',
    'zend_iterable' => 'zend_iterable',
    'zend_weakmap_attach' => 'zend_weakmap_attach',
    'zend_weakmap_remove' => 'zend_weakmap_remove',
    'zend_weakmap_dump' => 'zend_weakmap_dump',
    'zend_get_unit_enum' => 'zend_get_unit_enum',
    'zend_test_parameter_with_attribute' => 'zend_test_parameter_with_attribute',
    'zend_test_attribute_with_named_argument' => 'zend_test_attribute_with_named_argument',
    'zend_get_current_func_name' => 'zend_get_current_func_name',
    'zend_call_method' => 'zend_call_method',
    'zend_object_init_with_constructor' => 'zend_object_init_with_constructor',
    'zend_test_zend_ini_parse_quantity' => 'zend_test_zend_ini_parse_quantity',
    'zend_test_zend_ini_parse_uquantity' => 'zend_test_zend_ini_parse_uquantity',
    'zend_test_zend_ini_str' => 'zend_test_zend_ini_str',
    'zend_test_zend_call_stack_get' => 'zend_test_zend_call_stack_get',
    'zend_test_zend_call_stack_use_all' => 'zend_test_zend_call_stack_use_all',
    'zend_test_is_string_marked_as_valid_utf8' => 'zend_test_is_string_marked_as_valid_utf8',
    'zend_get_map_ptr_last' => 'zend_get_map_ptr_last',
    'zend_test_crash' => 'zend_test_crash',
    'zend_test_fill_packed_array' => 'zend_test_fill_packed_array',
    'zend_test_create_throwing_resource' => 'zend_test_create_throwing_resource',
    'get_open_basedir' => 'get_open_basedir',
    'zend_test_override_libxml_global_state' => 'zend_test_override_libxml_global_state',
    'zend_test_is_pcre_bundled' => 'zend_test_is_pcre_bundled',
    'zend_test_cast_fread' => 'zend_test_cast_fread',
    'zend_test_is_zend_ptr' => 'zend_test_is_zend_ptr',
    'ZendTestNS2\\namespaced_func' => 'ZendTestNS2\\namespaced_func',
    'ZendTestNS2\\namespaced_deprecated_func' => 'ZendTestNS2\\namespaced_deprecated_func',
    'ZendTestNS2\\namespaced_aliased_func' => 'ZendTestNS2\\namespaced_aliased_func',
    'ZendTestNS2\\namespaced_deprecated_aliased_func' => 'ZendTestNS2\\namespaced_deprecated_aliased_func',
    'ZendTestNS2\\ZendSubNS\\namespaced_func' => 'ZendTestNS2\\ZendSubNS\\namespaced_func',
    'ZendTestNS2\\ZendSubNS\\namespaced_deprecated_func' => 'ZendTestNS2\\ZendSubNS\\namespaced_deprecated_func',
    'ZendTestNS2\\ZendSubNS\\namespaced_aliased_func' => 'ZendTestNS2\\ZendSubNS\\namespaced_aliased_func',
    'ZendTestNS2\\ZendSubNS\\namespaced_deprecated_aliased_func' => 'ZendTestNS2\\ZendSubNS\\namespaced_deprecated_aliased_func',
    'zend_test_internal_dnf_arguments' => 'zend_test_internal_dnf_arguments',
    'zend_iterable_legacy' => 'zend_iterable_legacy',
  ),
  'constants' => 
  array (
    'ZEND_TEST_DEPRECATED' => 42,
    'ZEND_CONSTANT_A' => 'global',
    'ZendTestNS2\\ZEND_CONSTANT_A' => 'namespaced',
    'ZendTestNS2\\ZendSubNS\\ZEND_CONSTANT_A' => 'namespaced',
  ),
  'dependencies' => 
  array (
  ),
  'ini' => 
  array (
    'zend_test.limit_copy_file_range' => '-1',
    'zend_test.not_empty_str_test' => 'val',
    'zend_test.observe_opline_in_zendmm' => '0',
    'zend_test.observer.enabled' => '0',
    'zend_test.observer.execute_internal' => '0',
    'zend_test.observer.fiber_destroy' => '0',
    'zend_test.observer.fiber_init' => '0',
    'zend_test.observer.fiber_switch' => '0',
    'zend_test.observer.observe_all' => '0',
    'zend_test.observer.observe_declaring' => '0',
    'zend_test.observer.observe_function_names' => '',
    'zend_test.observer.observe_functions' => '0',
    'zend_test.observer.observe_includes' => '0',
    'zend_test.observer.show_init_backtrace' => '0',
    'zend_test.observer.show_opcode' => '0',
    'zend_test.observer.show_opcode_in_user_handler' => '',
    'zend_test.observer.show_output' => '1',
    'zend_test.observer.show_return_type' => '0',
    'zend_test.observer.show_return_value' => '0',
    'zend_test.print_stderr_mshutdown' => '0',
    'zend_test.quantity_value' => '0',
    'zend_test.register_passes' => '0',
    'zend_test.replace_zend_execute_ex' => '0',
    'zend_test.str_test' => '',
    'zend_test.zend_mm_custom_handlers.enabled' => '0',
  ),
);
