<?php

return array (
  'type' => 'class',
  'name' => 'ZMQ',
  'meta' => 
  array (
    'type' => 'class',
    'name' => 'ZMQ',
    'description' => '',
    'keywords' => 
    array (
    ),
    'added' => '0.0',
    'deprecated' => NULL,
    'removed' => NULL,
    'resources' => 
    array (
      0 => 
      array (
        'name' => 'ZMQ class (php.net)',
        'url' => 'https://www.php.net/manual/class.zmq.php',
      ),
    ),
  ),
  'interfaces' => 
  array (
  ),
  'constants' => 
  array (
    'SOCKET_PAIR' => 0,
    'SOCKET_PUB' => 1,
    'SOCKET_SUB' => 2,
    'SOCKET_REQ' => 3,
    'SOCKET_REP' => 4,
    'SOCKET_XREQ' => 5,
    'SOCKET_XREP' => 6,
    'SOCKET_PUSH' => 8,
    'SOCKET_PULL' => 7,
    'SOCKET_DEALER' => 5,
    'SOCKET_ROUTER' => 6,
    'SOCKET_XSUB' => 10,
    'SOCKET_XPUB' => 9,
    'SOCKET_STREAM' => 11,
    'SOCKET_UPSTREAM' => 7,
    'SOCKET_DOWNSTREAM' => 8,
    'POLL_IN' => 1,
    'POLL_OUT' => 2,
    'MODE_SNDMORE' => 2,
    'MODE_NOBLOCK' => 1,
    'MODE_DONTWAIT' => 1,
    'ERR_INTERNAL' => -99,
    'ERR_EAGAIN' => 11,
    'ERR_ENOTSUP' => 95,
    'ERR_EFSM' => 156384763,
    'ERR_ETERM' => 156384765,
    'LIBZMQ_VER' => '4.3.4',
    'LIBZMQ_VERSION' => '4.3.4',
    'LIBZMQ_VERSION_ID' => 40304,
    'LIBZMQ_VERSION_MAJOR' => 4,
    'LIBZMQ_VERSION_MINOR' => 3,
    'LIBZMQ_VERSION_PATCH' => 4,
    'SOCKOPT_GSSAPI_PRINCIPAL_NAMETYPE' => 90,
    'SOCKOPT_GSSAPI_SERVICE_PRINCIPAL_NAMETYPE' => 91,
    'SOCKOPT_BINDTODEVICE' => 92,
    'SOCKOPT_HEARTBEAT_IVL' => 75,
    'SOCKOPT_HEARTBEAT_TTL' => 76,
    'SOCKOPT_HEARTBEAT_TIMEOUT' => 77,
    'SOCKOPT_USE_FD' => 89,
    'SOCKOPT_XPUB_MANUAL' => 71,
    'SOCKOPT_XPUB_WELCOME_MSG' => 72,
    'SOCKOPT_STREAM_NOTIFY' => 73,
    'SOCKOPT_INVERT_MATCHING' => 74,
    'SOCKOPT_XPUB_VERBOSER' => 78,
    'SOCKOPT_CONNECT_TIMEOUT' => 79,
    'SOCKOPT_TCP_MAXRT' => 80,
    'SOCKOPT_THREAD_SAFE' => 81,
    'SOCKOPT_MULTICAST_MAXTPDU' => 84,
    'SOCKOPT_VMCI_BUFFER_SIZE' => 85,
    'SOCKOPT_VMCI_BUFFER_MIN_SIZE' => 86,
    'SOCKOPT_VMCI_BUFFER_MAX_SIZE' => 87,
    'SOCKOPT_VMCI_CONNECT_TIMEOUT' => 88,
    'SOCKOPT_TOS' => 57,
    'SOCKOPT_ROUTER_HANDOVER' => 56,
    'SOCKOPT_CONNECT_RID' => 61,
    'SOCKOPT_HANDSHAKE_IVL' => 66,
    'SOCKOPT_SOCKS_PROXY' => 68,
    'SOCKOPT_XPUB_NODROP' => 69,
    'SOCKOPT_ROUTER_MANDATORY' => 33,
    'SOCKOPT_PROBE_ROUTER' => 51,
    'SOCKOPT_REQ_RELAXED' => 53,
    'SOCKOPT_REQ_CORRELATE' => 52,
    'SOCKOPT_CONFLATE' => 54,
    'SOCKOPT_ZAP_DOMAIN' => 55,
    'SOCKOPT_MECHANISM' => 43,
    'SOCKOPT_PLAIN_SERVER' => 44,
    'SOCKOPT_PLAIN_USERNAME' => 45,
    'SOCKOPT_PLAIN_PASSWORD' => 46,
    'SOCKOPT_CURVE_SERVER' => 47,
    'SOCKOPT_CURVE_PUBLICKEY' => 48,
    'SOCKOPT_CURVE_SECRETKEY' => 49,
    'SOCKOPT_CURVE_SERVERKEY' => 50,
    'SOCKOPT_GSSAPI_SERVER' => 62,
    'SOCKOPT_GSSAPI_PLAINTEXT' => 65,
    'SOCKOPT_GSSAPI_PRINCIPAL' => 63,
    'SOCKOPT_GSSAPI_SERVICE_PRINCIPAL' => 64,
    'SOCKOPT_IPV6' => 42,
    'SOCKOPT_IMMEDIATE' => 39,
    'SOCKOPT_SNDHWM' => 23,
    'SOCKOPT_RCVHWM' => 24,
    'SOCKOPT_MAXMSGSIZE' => 22,
    'SOCKOPT_MULTICAST_HOPS' => 25,
    'SOCKOPT_XPUB_VERBOSE' => 40,
    'SOCKOPT_TCP_KEEPALIVE' => 34,
    'SOCKOPT_TCP_KEEPALIVE_IDLE' => 36,
    'SOCKOPT_TCP_KEEPALIVE_CNT' => 35,
    'SOCKOPT_TCP_KEEPALIVE_INTVL' => 37,
    'SOCKOPT_TCP_ACCEPT_FILTER' => 38,
    'SOCKOPT_LAST_ENDPOINT' => 32,
    'SOCKOPT_ROUTER_RAW' => 41,
    'SOCKOPT_IPV4ONLY' => 31,
    'SOCKOPT_DELAY_ATTACH_ON_CONNECT' => 39,
    'SOCKOPT_HWM' => 2001,
    'SOCKOPT_AFFINITY' => 4,
    'SOCKOPT_IDENTITY' => 5,
    'SOCKOPT_RATE' => 8,
    'SOCKOPT_RECOVERY_IVL' => 9,
    'SOCKOPT_RCVTIMEO' => 27,
    'SOCKOPT_SNDTIMEO' => 28,
    'SOCKOPT_SNDBUF' => 11,
    'SOCKOPT_RCVBUF' => 12,
    'SOCKOPT_LINGER' => 17,
    'SOCKOPT_RECONNECT_IVL' => 18,
    'SOCKOPT_RECONNECT_IVL_MAX' => 21,
    'SOCKOPT_BACKLOG' => 19,
    'SOCKOPT_SUBSCRIBE' => 6,
    'SOCKOPT_UNSUBSCRIBE' => 7,
    'SOCKOPT_TYPE' => 16,
    'SOCKOPT_RCVMORE' => 13,
    'SOCKOPT_FD' => 14,
    'SOCKOPT_EVENTS' => 15,
    'CTXOPT_MAX_SOCKETS' => 2,
    'CTXOPT_MAX_SOCKETS_DEFAULT' => 1023,
    'EVENT_CONNECTED' => 1,
    'EVENT_CONNECT_DELAYED' => 2,
    'EVENT_CONNECT_RETRIED' => 4,
    'EVENT_LISTENING' => 8,
    'EVENT_BIND_FAILED' => 16,
    'EVENT_ACCEPTED' => 32,
    'EVENT_ACCEPT_FAILED' => 64,
    'EVENT_CLOSED' => 128,
    'EVENT_CLOSE_FAILED' => 256,
    'EVENT_DISCONNECTED' => 512,
    'EVENT_MONITOR_STOPPED' => 1024,
    'EVENT_ALL' => 65535,
  ),
  'properties' => 
  array (
  ),
  'methods' => 
  array (
    '__construct' => 
    array (
      'name' => '__construct',
      'class' => 'ZMQ',
      'parameters' => 
      array (
      ),
      'return_type' => NULL,
      'has_return_type' => false,
      'is_static' => false,
      'is_public' => false,
      'is_protected' => false,
      'is_private' => true,
    ),
    'clock' => 
    array (
      'name' => 'clock',
      'class' => 'ZMQ',
      'parameters' => 
      array (
      ),
      'return_type' => NULL,
      'has_return_type' => false,
      'is_static' => true,
      'is_public' => true,
      'is_protected' => false,
      'is_private' => false,
    ),
    'z85encode' => 
    array (
      'name' => 'z85encode',
      'class' => 'ZMQ',
      'parameters' => 
      array (
        'data' => 
        array (
          'position' => 0,
          'name' => 'data',
          'type' => NULL,
          'is_optional' => false,
          'has_default_value' => false,
          'default_value' => NULL,
          'has_default_value_constant' => false,
          'default_value_constant' => NULL,
        ),
      ),
      'return_type' => NULL,
      'has_return_type' => false,
      'is_static' => true,
      'is_public' => true,
      'is_protected' => false,
      'is_private' => false,
    ),
    'z85decode' => 
    array (
      'name' => 'z85decode',
      'class' => 'ZMQ',
      'parameters' => 
      array (
        'data' => 
        array (
          'position' => 0,
          'name' => 'data',
          'type' => NULL,
          'is_optional' => false,
          'has_default_value' => false,
          'default_value' => NULL,
          'has_default_value_constant' => false,
          'default_value_constant' => NULL,
        ),
      ),
      'return_type' => NULL,
      'has_return_type' => false,
      'is_static' => true,
      'is_public' => true,
      'is_protected' => false,
      'is_private' => false,
    ),
    'curvekeypair' => 
    array (
      'name' => 'curvekeypair',
      'class' => 'ZMQ',
      'parameters' => 
      array (
      ),
      'return_type' => NULL,
      'has_return_type' => false,
      'is_static' => true,
      'is_public' => true,
      'is_protected' => false,
      'is_private' => false,
    ),
  ),
  'traits' => 
  array (
  ),
  'is_abstract' => false,
  'is_anonymous' => false,
  'is_cloneable' => true,
  'is_final' => false,
  'is_read_only' => false,
);
