<?php

return array (
  'type' => 'extension',
  'name' => 'xdebug',
  'meta' => 
  array (
    'type' => 'extension',
    'name' => 'xdebug',
    'description' => '',
    'keywords' => 
    array (
    ),
    'added' => '0.0',
    'deprecated' => 
    \ReflectionExtension::__set_state(array(
       'name' => 'xdebug',
    )),
    'removed' => NULL,
    'version' => '__DYNAMIC__PHP Version',
    'resources' => 
    array (
      0 => 
      array (
        'name' => 'xdebug extension (php.net)',
        'url' => 'https://www.php.net/manual/book.xdebug.php',
      ),
    ),
  ),
  'classes' => 
  array (
  ),
  'functions' => 
  array (
    'xdebug_break' => 'xdebug_break',
    'xdebug_call_class' => 'xdebug_call_class',
    'xdebug_call_file' => 'xdebug_call_file',
    'xdebug_call_function' => 'xdebug_call_function',
    'xdebug_call_line' => 'xdebug_call_line',
    'xdebug_code_coverage_started' => 'xdebug_code_coverage_started',
    'xdebug_connect_to_client' => 'xdebug_connect_to_client',
    'xdebug_debug_zval' => 'xdebug_debug_zval',
    'xdebug_debug_zval_stdout' => 'xdebug_debug_zval_stdout',
    'xdebug_dump_superglobals' => 'xdebug_dump_superglobals',
    'xdebug_get_code_coverage' => 'xdebug_get_code_coverage',
    'xdebug_get_collected_errors' => 'xdebug_get_collected_errors',
    'xdebug_get_function_count' => 'xdebug_get_function_count',
    'xdebug_get_function_stack' => 'xdebug_get_function_stack',
    'xdebug_get_gc_run_count' => 'xdebug_get_gc_run_count',
    'xdebug_get_gc_total_collected_roots' => 'xdebug_get_gc_total_collected_roots',
    'xdebug_get_gcstats_filename' => 'xdebug_get_gcstats_filename',
    'xdebug_get_headers' => 'xdebug_get_headers',
    'xdebug_get_monitored_functions' => 'xdebug_get_monitored_functions',
    'xdebug_get_profiler_filename' => 'xdebug_get_profiler_filename',
    'xdebug_get_stack_depth' => 'xdebug_get_stack_depth',
    'xdebug_get_tracefile_name' => 'xdebug_get_tracefile_name',
    'xdebug_info' => 'xdebug_info',
    'xdebug_is_debugger_active' => 'xdebug_is_debugger_active',
    'xdebug_memory_usage' => 'xdebug_memory_usage',
    'xdebug_notify' => 'xdebug_notify',
    'xdebug_peak_memory_usage' => 'xdebug_peak_memory_usage',
    'xdebug_print_function_stack' => 'xdebug_print_function_stack',
    'xdebug_set_filter' => 'xdebug_set_filter',
    'xdebug_start_code_coverage' => 'xdebug_start_code_coverage',
    'xdebug_start_error_collection' => 'xdebug_start_error_collection',
    'xdebug_start_function_monitor' => 'xdebug_start_function_monitor',
    'xdebug_start_gcstats' => 'xdebug_start_gcstats',
    'xdebug_start_trace' => 'xdebug_start_trace',
    'xdebug_stop_code_coverage' => 'xdebug_stop_code_coverage',
    'xdebug_stop_error_collection' => 'xdebug_stop_error_collection',
    'xdebug_stop_function_monitor' => 'xdebug_stop_function_monitor',
    'xdebug_stop_gcstats' => 'xdebug_stop_gcstats',
    'xdebug_stop_trace' => 'xdebug_stop_trace',
    'xdebug_time_index' => 'xdebug_time_index',
    'xdebug_var_dump' => 'xdebug_var_dump',
  ),
  'constants' => 
  array (
    'XDEBUG_CC_UNUSED' => 1,
    'XDEBUG_CC_DEAD_CODE' => 2,
    'XDEBUG_CC_BRANCH_CHECK' => 4,
    'XDEBUG_FILTER_CODE_COVERAGE' => 256,
    'XDEBUG_FILTER_STACK' => 512,
    'XDEBUG_FILTER_TRACING' => 768,
    'XDEBUG_FILTER_NONE' => 0,
    'XDEBUG_PATH_INCLUDE' => 1,
    'XDEBUG_PATH_EXCLUDE' => 2,
    'XDEBUG_NAMESPACE_INCLUDE' => 17,
    'XDEBUG_NAMESPACE_EXCLUDE' => 18,
    'XDEBUG_TRACE_APPEND' => 1,
    'XDEBUG_TRACE_COMPUTERIZED' => 2,
    'XDEBUG_TRACE_FLAMEGRAPH_COST' => 16,
    'XDEBUG_TRACE_FLAMEGRAPH_MEM' => 32,
    'XDEBUG_TRACE_HTML' => 4,
    'XDEBUG_TRACE_NAKED_FILENAME' => 8,
  ),
  'dependencies' => 
  array (
  ),
  'ini' => 
  array (
    'xdebug.auto_trace' => 'This setting has been changed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.auto_trace',
    'xdebug.cli_color' => '0',
    'xdebug.client_discovery_header' => 'HTTP_X_FORWARDED_FOR,REMOTE_ADDR',
    'xdebug.client_host' => 'localhost',
    'xdebug.client_port' => '9003',
    'xdebug.cloud_id' => '',
    'xdebug.collect_assignments' => '0',
    'xdebug.collect_includes' => 'This setting has been removed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#removed-xdebug.collect_includes',
    'xdebug.collect_params' => '1',
    'xdebug.collect_return' => '0',
    'xdebug.collect_vars' => 'This setting has been removed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#removed-xdebug.collect_vars',
    'xdebug.connect_timeout_ms' => '200',
    'xdebug.control_socket' => 'default',
    'xdebug.coverage_enable' => 'This setting has been changed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.coverage_enable',
    'xdebug.default_enable' => 'This setting has been changed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.default_enable',
    'xdebug.discover_client_host' => '0',
    'xdebug.dump.COOKIE' => NULL,
    'xdebug.dump.ENV' => NULL,
    'xdebug.dump.FILES' => NULL,
    'xdebug.dump.GET' => NULL,
    'xdebug.dump.POST' => NULL,
    'xdebug.dump.REQUEST' => NULL,
    'xdebug.dump.SERVER' => NULL,
    'xdebug.dump.SESSION' => NULL,
    'xdebug.dump_globals' => '1',
    'xdebug.dump_once' => '1',
    'xdebug.dump_undefined' => '0',
    'xdebug.file_link_format' => '',
    'xdebug.filename_format' => '',
    'xdebug.force_display_errors' => '0',
    'xdebug.force_error_reporting' => '0',
    'xdebug.gc_stats_enable' => 'This setting has been changed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.gc_stats_enable',
    'xdebug.gc_stats_output_dir' => 'This setting has been changed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.gc_stats_output_dir',
    'xdebug.gc_stats_output_name' => 'gcstats.%p',
    'xdebug.halt_level' => '0',
    'xdebug.idekey' => '',
    'xdebug.log' => '',
    'xdebug.log_level' => '7',
    'xdebug.max_nesting_level' => '512',
    'xdebug.max_stack_frames' => '-1',
    'xdebug.mode' => 'coverage',
    'xdebug.output_dir' => '/tmp',
    'xdebug.overload_var_dump' => 'This setting has been removed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#removed-xdebug.overload_var_dump',
    'xdebug.profiler_append' => '0',
    'xdebug.profiler_enable' => 'This setting has been changed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.profiler_enable',
    'xdebug.profiler_enable_trigger' => 'This setting has been changed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.profiler_enable_trigger',
    'xdebug.profiler_enable_trigger_value' => 'This setting has been changed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.profiler_enable_trigger_value',
    'xdebug.profiler_output_dir' => 'This setting has been changed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.profiler_output_dir',
    'xdebug.profiler_output_name' => 'cachegrind.out.%p',
    'xdebug.remote_autostart' => 'This setting has been changed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_autostart',
    'xdebug.remote_connect_back' => 'This setting has been changed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_connect_back',
    'xdebug.remote_enable' => 'This setting has been changed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_enable',
    'xdebug.remote_host' => 'This setting has been changed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_host',
    'xdebug.remote_log' => 'This setting has been changed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_log',
    'xdebug.remote_log_level' => 'This setting has been changed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_log_level',
    'xdebug.remote_mode' => 'This setting has been changed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_mode',
    'xdebug.remote_port' => 'This setting has been changed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_port',
    'xdebug.remote_timeout' => 'This setting has been changed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_timeout',
    'xdebug.scream' => '0',
    'xdebug.show_error_trace' => '0',
    'xdebug.show_exception_trace' => '0',
    'xdebug.show_local_vars' => '0',
    'xdebug.show_mem_delta' => 'This setting has been removed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#removed-xdebug.show_mem_delta',
    'xdebug.start_upon_error' => 'default',
    'xdebug.start_with_request' => 'default',
    'xdebug.trace_enable_trigger' => 'This setting has been changed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.trace_enable_trigger',
    'xdebug.trace_enable_trigger_value' => 'This setting has been changed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.trace_enable_trigger_value',
    'xdebug.trace_format' => '0',
    'xdebug.trace_options' => '0',
    'xdebug.trace_output_dir' => 'This setting has been changed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.trace_output_dir',
    'xdebug.trace_output_name' => 'trace.%c',
    'xdebug.trigger_value' => '',
    'xdebug.use_compression' => '1',
    'xdebug.var_display_max_children' => '128',
    'xdebug.var_display_max_data' => '512',
    'xdebug.var_display_max_depth' => '3',
  ),
);
