<?php

return array (
  'type' => 'extension',
  'name' => 'mssql',
  'meta' => 
  array (
    'type' => 'extension',
    'name' => 'mssql',
    'description' => '',
    'keywords' => 
    array (
    ),
    'added' => '0.0',
    'deprecated' => 
    ReflectionExtension::__set_state(array(
       'name' => 'mssql',
    )),
    'removed' => NULL,
    'version' => '__DYNAMIC__PHP Version',
    'resources' => 
    array (
      0 => 
      array (
        'name' => 'mssql extension (php.net)',
        'url' => 'https://www.php.net/manual/book.mssql.php',
      ),
    ),
  ),
  'classes' => 
  array (
  ),
  'functions' => 
  array (
    'mssql_connect' => 'mssql_connect',
    'mssql_pconnect' => 'mssql_pconnect',
    'mssql_close' => 'mssql_close',
    'mssql_select_db' => 'mssql_select_db',
    'mssql_query' => 'mssql_query',
    'mssql_fetch_batch' => 'mssql_fetch_batch',
    'mssql_rows_affected' => 'mssql_rows_affected',
    'mssql_free_result' => 'mssql_free_result',
    'mssql_get_last_message' => 'mssql_get_last_message',
    'mssql_num_rows' => 'mssql_num_rows',
    'mssql_num_fields' => 'mssql_num_fields',
    'mssql_fetch_field' => 'mssql_fetch_field',
    'mssql_fetch_row' => 'mssql_fetch_row',
    'mssql_fetch_array' => 'mssql_fetch_array',
    'mssql_fetch_assoc' => 'mssql_fetch_assoc',
    'mssql_fetch_object' => 'mssql_fetch_object',
    'mssql_field_length' => 'mssql_field_length',
    'mssql_field_name' => 'mssql_field_name',
    'mssql_field_type' => 'mssql_field_type',
    'mssql_data_seek' => 'mssql_data_seek',
    'mssql_field_seek' => 'mssql_field_seek',
    'mssql_result' => 'mssql_result',
    'mssql_next_result' => 'mssql_next_result',
    'mssql_min_error_severity' => 'mssql_min_error_severity',
    'mssql_min_message_severity' => 'mssql_min_message_severity',
    'mssql_init' => 'mssql_init',
    'mssql_bind' => 'mssql_bind',
    'mssql_execute' => 'mssql_execute',
    'mssql_free_statement' => 'mssql_free_statement',
    'mssql_guid_string' => 'mssql_guid_string',
    'sybase_connect' => 'sybase_connect',
    'sybase_pconnect' => 'sybase_pconnect',
    'sybase_close' => 'sybase_close',
    'sybase_select_db' => 'sybase_select_db',
    'sybase_query' => 'sybase_query',
    'sybase_fetch_batch' => 'sybase_fetch_batch',
    'sybase_affected_rows' => 'sybase_affected_rows',
    'sybase_free_result' => 'sybase_free_result',
    'sybase_get_last_message' => 'sybase_get_last_message',
    'sybase_num_rows' => 'sybase_num_rows',
    'sybase_num_fields' => 'sybase_num_fields',
    'sybase_fetch_field' => 'sybase_fetch_field',
    'sybase_fetch_row' => 'sybase_fetch_row',
    'sybase_fetch_array' => 'sybase_fetch_array',
    'sybase_fetch_assoc' => 'sybase_fetch_assoc',
    'sybase_fetch_object' => 'sybase_fetch_object',
    'sybase_field_length' => 'sybase_field_length',
    'sybase_field_name' => 'sybase_field_name',
    'sybase_field_type' => 'sybase_field_type',
    'sybase_data_seek' => 'sybase_data_seek',
    'sybase_field_seek' => 'sybase_field_seek',
    'sybase_result' => 'sybase_result',
    'sybase_next_result' => 'sybase_next_result',
    'sybase_min_error_severity' => 'sybase_min_error_severity',
    'sybase_min_message_severity' => 'sybase_min_message_severity',
    'sybase_init' => 'sybase_init',
    'sybase_bind' => 'sybase_bind',
    'sybase_execute' => 'sybase_execute',
    'sybase_free_statement' => 'sybase_free_statement',
    'sybase_guid_string' => 'sybase_guid_string',
  ),
  'constants' => 
  array (
    'MSSQL_ASSOC' => 1,
    'MSSQL_NUM' => 2,
    'MSSQL_BOTH' => 3,
    'SQLTEXT' => 35,
    'SQLVARCHAR' => 39,
    'SQLCHAR' => 47,
    'SQLINT1' => 48,
    'SQLINT2' => 52,
    'SQLINT4' => 56,
    'SQLBIT' => 50,
    'SQLFLT4' => 59,
    'SQLFLT8' => 62,
    'SQLFLTN' => 109,
  ),
  'dependencies' => 
  array (
  ),
  'ini' => 
  array (
    'mssql.allow_persistent' => '1',
    'mssql.batchsize' => '0',
    'mssql.charset' => '',
    'mssql.compatability_mode' => '0',
    'mssql.compatibility_mode' => '',
    'mssql.connect_timeout' => '5',
    'mssql.datetimeconvert' => '1',
    'mssql.max_links' => '-1',
    'mssql.max_persistent' => '-1',
    'mssql.max_procs' => '-1',
    'mssql.min_error_severity' => '10',
    'mssql.min_message_severity' => '10',
    'mssql.secure_connection' => '',
    'mssql.textlimit' => '-1',
    'mssql.textsize' => '-1',
    'mssql.timeout' => '60',
  ),
);
