<?php

return array (
  'Traversable',
  'IteratorAggregate',
  'Iterator',
  'ArrayAccess',
  'Serializable',
  'DateTimeInterface',
  'Reflector',
  'RecursiveIterator',
  'OuterIterator',
  'Countable',
  'SeekableIterator',
  'SplObserver',
  'SplSubject',
  'SessionHandlerInterface',
  'SessionIdInterface',
  'JsonSerializable',
  'MongoCursorInterface',
  'MongoDB\\Driver\\Exception\\Exception',
  'MongoDB\\BSON\\Type',
  'MongoDB\\BSON\\Serializable',
  'MongoDB\\BSON\\Unserializable',
  'MongoDB\\BSON\\Persistable',
  'http\\Exception',
  'http\\Client\\Curl\\User',
);
